/* Generated By:JJTree: Do not edit this line. ASTArrayLength.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayLength extends Expression {
  protected Expression arrayRef;

  public ASTArrayLength(int id) {
    super(id);
  }

  public ASTArrayLength(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f8775333fd9ffeb990d54271f0f6278 (do not edit this line) */
