/* Generated By:JJTree: Do not edit this line. ASTArrayCreation.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayCreation extends Expression {
  protected Expression size;

  public ASTArrayCreation(int id) {
    super(id);
  }

  public ASTArrayCreation(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a55d11e209245c684a60771f3bcb4b0b (do not edit this line) */
