/* Generated By:JJTree: Do not edit this line. ASTBranch.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBranch extends Statement {
  protected Expression condition;
  protected Statement thenStatement;
  protected Statement elseStatement;

  public ASTBranch(int id) {
    super(id);
  }

  public ASTBranch(MyGrammar p, int id) {
    super(p, id);
  }

  @Override
  public void dump(String prefix) {
    System.out.println(toString(prefix));
    System.out.printf("%s\tCondition:\n", prefix);
    condition.dump(prefix + "\t\t");
    System.out.printf("%s\tThen:\n", prefix);
    thenStatement.dump(prefix + "\t\t");
    System.out.printf("%s\tElse:\n", prefix);
    elseStatement.dump(prefix + "\t\t");
  }
}
/* JavaCC - OriginalChecksum=82bf9e9154f4c386dcef3ed1b685eed3 (do not edit this line) */
