/* Generated By:JJTree: Do not edit this line. ASTClassImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassImport extends ASTImport {
  public ASTClassImport(int id) {
    super(id);
  }

  public ASTClassImport(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a0532b1a6e225d4028b11d1bbf12fd42 (do not edit this line) */
