/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDiv extends BinOpExpression {
  public ASTDiv(int id) {
    super(id);
    this.type = "int";
  }

  public ASTDiv(MyGrammar p, int id) {
    super(p, id);
    this.type = "int";
  }

  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    visitor.visit(this, data);

    left.jjtAccept(visitor, data);
    right.jjtAccept(visitor, data);

    return data;
  }
}
/* JavaCC - OriginalChecksum=b61b5577a877251ec1d392b9477044b5 (do not edit this line) */
