/* Generated By:JJTree: Do not edit this line. ASTExprStatement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExprStatement extends Statement {
  protected Expression expression;

  public ASTExprStatement(int id) {
    super(id);
  }

  public ASTExprStatement(MyGrammar p, int id) {
    super(p, id);
  }

  @Override
  public void dump(String prefix) {
      expression.dump(prefix);
  }

  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=988a6c04c7c47489c995959a538df7d2 (do not edit this line) */
