/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionCall extends Expression {
  protected Expression ownerRef;
  protected String identifier;

  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=33fb9ed4dec67bbb1d82c4764f788c5f (do not edit this line) */
