import java.util.HashMap;

/* Generated By:JJTree: Do not edit this line. ASTImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImport extends SimpleNode {
  public HashMap<String, String> symbol_table = new HashMap<String, String>();

  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebd8a9e29bc3379d0878fc8b9703f9d2 (do not edit this line) */
