/* Generated By:JJTree: Do not edit this line. ASTMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethod extends SimpleNode {
  protected String identifier;
  protected String type;

  public ASTMethod(int id) {
    super(id);
  }

  public ASTMethod(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e520198b9ad9d425775d48b35053f06f (do not edit this line) */
