import java.util.HashMap;

/* Generated By:JJTree: Do not edit this line. ASTMainMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethod extends ASTMethod {
  public HashMap<id, String> symbol_table = new HashMap<id, String>();

  public ASTMainMethod(int id) {
    super(id);
    this.type = "void";
    this.identifier = "main";
  }

  public ASTMainMethod(MyGrammar p, int id) {
    super(p, id);
    this.type = "void";
    this.identifier = "main";
  }

}
/* JavaCC - OriginalChecksum=eaba5dd4ffdd5af0c1e9268123cbd273 (do not edit this line) */
