/* Generated By:JJTree: Do not edit this line. ASTMainContainer.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainContainer extends SimpleNode {
  public ASTMainContainer(int id) {
    super(id);
  }

  public ASTMainContainer(MyGrammar p, int id) {
    super(p, id);
  }


  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fb085d7218f1a07edc710dca82ded227 (do not edit this line) */
