/* Generated By:JJTree: Do not edit this line. ASTNegation.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNegation extends Expression {
  protected Expression child;

  public ASTNegation(int id) {
    super(id);
  }

  public ASTNegation(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48b7763635cf5b147f70ac01b5969500 (do not edit this line) */
