/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8958c394ec71e4c951c05f67dbb8c665 (do not edit this line) */
