/* Generated By:JJTree: Do not edit this line. ASTWhileLoop.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileLoop extends Statement {
  protected Expression condition;
  protected Statement body;

  public ASTWhileLoop(int id) {
    super(id);
  }

  public ASTWhileLoop(MyGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c1356b15eb614280454e4920a4588d9 (do not edit this line) */
