/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFunctionCall extends Expression {
  public Expression ownerRef;
  public String identifier;
  public ASTArguments arguments;

  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(MyGrammar p, int id) {
    super(p, id);
  }

  @Override
  public void dump(String prefix) {
    System.out.println(toString(prefix));
    System.out.printf("%s Function name: %s\n", prefix, identifier);
    System.out.printf("%s Owner Reference:\n", prefix);
    ownerRef.dump(prefix+"  ");

    arguments.dump(prefix + " ");
  }

  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33fb9ed4dec67bbb1d82c4764f788c5f (do not edit this line) */
