/* Generated By:JJTree: Do not edit this line. ASTMethodList.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMethodList extends SimpleNode {
  public ASTMethodList(int id) {
    super(id);
  }

  public ASTMethodList(MyGrammar p, int id) {
    super(p, id);
  }


  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c330d1c636b0d9b7425dac8e55d99ca6 (do not edit this line) */
