/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSub extends BinOpExpression {
  public ASTSub(int id) {
    super(id);
  }

  public ASTSub(MyGrammar p, int id) {
    super(p, id);
  }

  @Override
  public Object jjtAccept(MyGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bfb61ee7c75babb3e92617c46c5a0691 (do not edit this line) */
