/* Generated By:JavaCC: Do not edit this line. MyGrammarVisitor.java Version 6.1_2 */

import parser.*;
import symbolTable.StMethod;

public class SemanticVisitor implements MyGrammarVisitor
{
    @Override
    public Object visit(SimpleNode node, Object data) {
        return null;
    }



    @Override
    public Object visit(ASTClass node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTVarDeclarationsList node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTMethodList node, Object data) {
        return null;
    }


    @Override
    public Object visit(ASTVar node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTMethod node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTStatementList node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTReturnStatement node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTMainMethod node, Object data) {
        return null;
    }


    @Override
    public Object visit(ASTScopedStatementList node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTAssignment node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTBranch node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTWhileLoop node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTArrayAssignment node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTExprStatement node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTArrayAccess node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTLiteral node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTVarReference node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTSelfReference node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTArrayCreation node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTConstructorCall node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTNegation node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTArrayLength node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTFunctionCall node, Object data) {
        return null;
    }


    @Override
    public Object visit(ASTAnd node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTLessThan node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTSum node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTSub node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTMul node, Object data) {
        return null;
    }

    @Override
    public Object visit(ASTDiv node, Object data) {
        return null;
    }

    @Override 
    public Object visit(ASTParameters node, Object data){
       return null;
        



    }
    @Override 
    public Object visit(ASTArgument node, Object data){
        return null;
    }

    @Override 
    public Object visit(ASTArgumentList node, Object data){
        return null;
    }

    @Override 
    public Object visit(ASTStaticMethodImport node, Object data){
        return null;
    }

    @Override 
    public Object visit(ASTMethodImport node, Object data){
        return null;
    }

    @Override 
    public Object visit(ASTProgram node, Object data){
        return null;
    }

}
/* JavaCC - OriginalChecksum=f4b465338f5f535900f88d4b62af7c27 (do not edit this line) */
